/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'unmesh' at '13/5/16 10:02 AM' with Gradle 2.5
 *
 * @author unmesh, @date 13/5/16 10:02 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
