- apt: name={{item}}
  with_items:
    - libsnappy-dev
    - asciidoc
    - g++
    - libjansson-dev
    - libcurl4-openssl-dev
    - git
    - pkg-config
    - cmake

- name: ensure /usr/local/lib/pkgconfig/libsnappy.pc file exists
  blockinfile:
    dest: /usr/local/lib/pkgconfig/libsnappy.pc
    create: yes
    owner: root
    block: |
      Name: libsnappy
      Description: Snappy is a compression library
      Version: 1.1.2
      URL: https://google.github.io/snappy/
      Libs: -L/usr/local/lib -lsnappy
      Cflags: -I/usr/local/include
